name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. EC2 서버로 코드 업로드 및 배포
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            # 배포 디렉터리로 이동
            cd /home/ec2-user/project-directory

            # 최신 코드 가져오기
            git pull origin main

            # Docker Compose 또는 애플리케이션 재시작
            docker-compose down
            docker-compose up -d --build
          EOF